[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=0.3.5",
    "langchain-openai>=0.3.27",
    "mcp>=1.10.1",
    "mcp-use>=1.3.3",
    "use>=0.1.0",
]
